//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svrCUO
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pcm.pide.gob.pe/webservice", ConfigurationName="svrCUO.PcmCuoPortType")]
    public interface PcmCuoPortType
    {
        
        // CODEGEN: Se está generando un empleado de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://pcm.pide.gob.pe/webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://pcm.pide.gob.pe/webservice#ShowArchivos", ReplyAction="http://pcm.pide.gob.pe/webservice/ApplicationServicesPortType/getCUOEntidadRespon" +
            "se")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        svrCUO.getCUOEntidadResponse getCUOEntidad(svrCUO.getCUOEntidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcm.pide.gob.pe/webservice#ShowArchivos", ReplyAction="http://pcm.pide.gob.pe/webservice/ApplicationServicesPortType/getCUOEntidadRespon" +
            "se")]
        System.Threading.Tasks.Task<svrCUO.getCUOEntidadResponse> getCUOEntidadAsync(svrCUO.getCUOEntidadRequest request);
        
        // CODEGEN: Se está generando un empleado de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://pcm.pide.gob.pe/webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://pcm.pide.gob.pe/webservice#ShowArchivo", ReplyAction="http://pcm.pide.gob.pe/webservice/ApplicationServicesPortType/getCUOResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        svrCUO.getCUOResponse getCUO(svrCUO.getCUORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcm.pide.gob.pe/webservice#ShowArchivo", ReplyAction="http://pcm.pide.gob.pe/webservice/ApplicationServicesPortType/getCUOResponse")]
        System.Threading.Tasks.Task<svrCUO.getCUOResponse> getCUOAsync(svrCUO.getCUORequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCUOEntidad", WrapperNamespace="http://pcm.pide.gob.pe/webservice", IsWrapped=true)]
    public partial class getCUOEntidadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string servicio;
        
        public getCUOEntidadRequest()
        {
        }
        
        public getCUOEntidadRequest(string ruc, string servicio)
        {
            this.ruc = ruc;
            this.servicio = servicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCUOEntidadResponse", WrapperNamespace="http://pcm.pide.gob.pe/webservice", IsWrapped=true)]
    public partial class getCUOEntidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getCUOEntidadResponse()
        {
        }
        
        public getCUOEntidadResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCUO", WrapperNamespace="http://pcm.pide.gob.pe/webservice", IsWrapped=true)]
    public partial class getCUORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ip;
        
        public getCUORequest()
        {
        }
        
        public getCUORequest(string ip)
        {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCUOResponse", WrapperNamespace="http://pcm.pide.gob.pe/webservice", IsWrapped=true)]
    public partial class getCUOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getCUOResponse()
        {
        }
        
        public getCUOResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PcmCuoPortTypeChannel : svrCUO.PcmCuoPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PcmCuoPortTypeClient : System.ServiceModel.ClientBase<svrCUO.PcmCuoPortType>, svrCUO.PcmCuoPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PcmCuoPortTypeClient() : 
                base(PcmCuoPortTypeClient.GetDefaultBinding(), PcmCuoPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PcmCuoHttpsSoap11Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PcmCuoPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(PcmCuoPortTypeClient.GetBindingForEndpoint(endpointConfiguration), PcmCuoPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PcmCuoPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PcmCuoPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PcmCuoPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PcmCuoPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PcmCuoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        svrCUO.getCUOEntidadResponse svrCUO.PcmCuoPortType.getCUOEntidad(svrCUO.getCUOEntidadRequest request)
        {
            return base.Channel.getCUOEntidad(request);
        }
        
        public string getCUOEntidad(string ruc, string servicio)
        {
            svrCUO.getCUOEntidadRequest inValue = new svrCUO.getCUOEntidadRequest();
            inValue.ruc = ruc;
            inValue.servicio = servicio;
            svrCUO.getCUOEntidadResponse retVal = ((svrCUO.PcmCuoPortType)(this)).getCUOEntidad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrCUO.getCUOEntidadResponse> svrCUO.PcmCuoPortType.getCUOEntidadAsync(svrCUO.getCUOEntidadRequest request)
        {
            return base.Channel.getCUOEntidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrCUO.getCUOEntidadResponse> getCUOEntidadAsync(string ruc, string servicio)
        {
            svrCUO.getCUOEntidadRequest inValue = new svrCUO.getCUOEntidadRequest();
            inValue.ruc = ruc;
            inValue.servicio = servicio;
            return ((svrCUO.PcmCuoPortType)(this)).getCUOEntidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        svrCUO.getCUOResponse svrCUO.PcmCuoPortType.getCUO(svrCUO.getCUORequest request)
        {
            return base.Channel.getCUO(request);
        }
        
        public string getCUO(string ip)
        {
            svrCUO.getCUORequest inValue = new svrCUO.getCUORequest();
            inValue.ip = ip;
            svrCUO.getCUOResponse retVal = ((svrCUO.PcmCuoPortType)(this)).getCUO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrCUO.getCUOResponse> svrCUO.PcmCuoPortType.getCUOAsync(svrCUO.getCUORequest request)
        {
            return base.Channel.getCUOAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrCUO.getCUOResponse> getCUOAsync(string ip)
        {
            svrCUO.getCUORequest inValue = new svrCUO.getCUORequest();
            inValue.ip = ip;
            return ((svrCUO.PcmCuoPortType)(this)).getCUOAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PcmCuoHttpsSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PcmCuoHttpsSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://ws3.pide.gob.pe/services/PcmCuo.PcmCuoHttpsSoap11Endpoint");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PcmCuoPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.PcmCuoHttpsSoap11Endpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PcmCuoPortTypeClient.GetEndpointAddress(EndpointConfiguration.PcmCuoHttpsSoap11Endpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            PcmCuoHttpsSoap11Endpoint,
        }
    }
}
