//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svrIOTramiteDesarrollo
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class IOException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class RespuestaConsultaTramite
    {
        
        private string vcodresField;
        
        private string vdesresField;
        
        private string vcuoField;
        
        private string vcuorefField;
        
        private string vnumregstdField;
        
        private string vanioregstdField;
        
        private string vuniorgstdField;
        
        private System.DateTime dfecregstdField;
        
        private bool dfecregstdFieldSpecified;
        
        private string vusuregstdField;
        
        private byte[] bcarstdField;
        
        private string vobsField;
        
        private string cflgestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vcodres
        {
            get
            {
                return this.vcodresField;
            }
            set
            {
                this.vcodresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vdesres
        {
            get
            {
                return this.vdesresField;
            }
            set
            {
                this.vdesresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vcuo
        {
            get
            {
                return this.vcuoField;
            }
            set
            {
                this.vcuoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vcuoref
        {
            get
            {
                return this.vcuorefField;
            }
            set
            {
                this.vcuorefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vnumregstd
        {
            get
            {
                return this.vnumregstdField;
            }
            set
            {
                this.vnumregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vanioregstd
        {
            get
            {
                return this.vanioregstdField;
            }
            set
            {
                this.vanioregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vuniorgstd
        {
            get
            {
                return this.vuniorgstdField;
            }
            set
            {
                this.vuniorgstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime dfecregstd
        {
            get
            {
                return this.dfecregstdField;
            }
            set
            {
                this.dfecregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dfecregstdSpecified
        {
            get
            {
                return this.dfecregstdFieldSpecified;
            }
            set
            {
                this.dfecregstdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vusuregstd
        {
            get
            {
                return this.vusuregstdField;
            }
            set
            {
                this.vusuregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] bcarstd
        {
            get
            {
                return this.bcarstdField;
            }
            set
            {
                this.bcarstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string vobs
        {
            get
            {
                return this.vobsField;
            }
            set
            {
                this.vobsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cflgest
        {
            get
            {
                return this.cflgestField;
            }
            set
            {
                this.cflgestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class ConsultaTramite
    {
        
        private string vrucentremField;
        
        private string vrucentrecField;
        
        private string vcuoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vrucentrem
        {
            get
            {
                return this.vrucentremField;
            }
            set
            {
                this.vrucentremField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vrucentrec
        {
            get
            {
                return this.vrucentrecField;
            }
            set
            {
                this.vrucentrecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vcuo
        {
            get
            {
                return this.vcuoField;
            }
            set
            {
                this.vcuoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class RespuestaCargoTramite
    {
        
        private string vcodresField;
        
        private string vdesresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vcodres
        {
            get
            {
                return this.vcodresField;
            }
            set
            {
                this.vcodresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vdesres
        {
            get
            {
                return this.vdesresField;
            }
            set
            {
                this.vdesresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class CargoTramite
    {
        
        private string vrucentremField;
        
        private string vrucentrecField;
        
        private string vcuoField;
        
        private string vcuorefField;
        
        private string vnumregstdField;
        
        private string vanioregstdField;
        
        private System.DateTime dfecregstdField;
        
        private string vuniorgstdField;
        
        private string vusuregstdField;
        
        private byte[] bcarstdField;
        
        private string vobsField;
        
        private string cflgestField;
        
        private string vdesanxstdrecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vrucentrem
        {
            get
            {
                return this.vrucentremField;
            }
            set
            {
                this.vrucentremField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vrucentrec
        {
            get
            {
                return this.vrucentrecField;
            }
            set
            {
                this.vrucentrecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vcuo
        {
            get
            {
                return this.vcuoField;
            }
            set
            {
                this.vcuoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vcuoref
        {
            get
            {
                return this.vcuorefField;
            }
            set
            {
                this.vcuorefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vnumregstd
        {
            get
            {
                return this.vnumregstdField;
            }
            set
            {
                this.vnumregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vanioregstd
        {
            get
            {
                return this.vanioregstdField;
            }
            set
            {
                this.vanioregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime dfecregstd
        {
            get
            {
                return this.dfecregstdField;
            }
            set
            {
                this.dfecregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string vuniorgstd
        {
            get
            {
                return this.vuniorgstdField;
            }
            set
            {
                this.vuniorgstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vusuregstd
        {
            get
            {
                return this.vusuregstdField;
            }
            set
            {
                this.vusuregstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] bcarstd
        {
            get
            {
                return this.bcarstdField;
            }
            set
            {
                this.bcarstdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string vobs
        {
            get
            {
                return this.vobsField;
            }
            set
            {
                this.vobsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cflgest
        {
            get
            {
                return this.cflgestField;
            }
            set
            {
                this.cflgestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string vdesanxstdrec
        {
            get
            {
                return this.vdesanxstdrecField;
            }
            set
            {
                this.vdesanxstdrecField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", ConfigurationName="svrIOTramiteDesarrollo.IOTramite")]
    public interface IOTramite
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.cargoResponseResponse> cargoResponseAsync(svrIOTramiteDesarrollo.cargoResponse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(svrIOTramiteDesarrollo.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.consultarTramiteResponseResponse> consultarTramiteResponseAsync(svrIOTramiteDesarrollo.consultarTramiteResponse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.getTipoDocumentoResponse> getTipoDocumentoAsync(svrIOTramiteDesarrollo.getTipoDocumento request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.recepcionarTramiteResponseResponse> recepcionarTramiteResponseAsync(svrIOTramiteDesarrollo.recepcionarTramiteResponse request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargoResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class cargoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.CargoTramite request;
        
        public cargoResponse()
        {
        }
        
        public cargoResponse(svrIOTramiteDesarrollo.CargoTramite request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargoResponseResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class cargoResponseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.RespuestaCargoTramite @return;
        
        public cargoResponseResponse()
        {
        }
        
        public cargoResponseResponse(svrIOTramiteDesarrollo.RespuestaCargoTramite @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarTramiteResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class consultarTramiteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.ConsultaTramite request;
        
        public consultarTramiteResponse()
        {
        }
        
        public consultarTramiteResponse(svrIOTramiteDesarrollo.ConsultaTramite request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarTramiteResponseResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class consultarTramiteResponseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.RespuestaConsultaTramite @return;
        
        public consultarTramiteResponseResponse()
        {
        }
        
        public consultarTramiteResponseResponse(svrIOTramiteDesarrollo.RespuestaConsultaTramite @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class ioTipoDocumentoTramite
    {
        
        private string ccodtipdoctraField;
        
        private string vnomtipdoctraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ccodtipdoctra
        {
            get
            {
                return this.ccodtipdoctraField;
            }
            set
            {
                this.ccodtipdoctraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vnomtipdoctra
        {
            get
            {
                return this.vnomtipdoctraField;
            }
            set
            {
                this.vnomtipdoctraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTipoDocumento", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class getTipoDocumento
    {
        
        public getTipoDocumento()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTipoDocumentoResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class getTipoDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.ioTipoDocumentoTramite[] @return;
        
        public getTipoDocumentoResponse()
        {
        }
        
        public getTipoDocumentoResponse(svrIOTramiteDesarrollo.ioTipoDocumentoTramite[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class RecepcionTramite
    {
        
        private string vrucentremField;
        
        private string vrucentrecField;
        
        private string vnomentemiField;
        
        private string vuniorgremField;
        
        private string vcuoField;
        
        private string vcuorefField;
        
        private string ccodtipdocField;
        
        private string vnumdocField;
        
        private System.DateTime dfecdocField;
        
        private string vuniorgdstField;
        
        private string vnomdstField;
        
        private string vnomcardstField;
        
        private string vasuField;
        
        private int snumanxField;
        
        private int snumfolField;
        
        private byte[] bpdfdocField;
        
        private string vnomdocField;
        
        private DocumentoAnexo[] lstanexosField;
        
        private string vurldocanxField;
        
        private string ctipdocideremField;
        
        private string vnumdocideremField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vrucentrem
        {
            get
            {
                return this.vrucentremField;
            }
            set
            {
                this.vrucentremField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vrucentrec
        {
            get
            {
                return this.vrucentrecField;
            }
            set
            {
                this.vrucentrecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vnomentemi
        {
            get
            {
                return this.vnomentemiField;
            }
            set
            {
                this.vnomentemiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vuniorgrem
        {
            get
            {
                return this.vuniorgremField;
            }
            set
            {
                this.vuniorgremField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vcuo
        {
            get
            {
                return this.vcuoField;
            }
            set
            {
                this.vcuoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vcuoref
        {
            get
            {
                return this.vcuorefField;
            }
            set
            {
                this.vcuorefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ccodtipdoc
        {
            get
            {
                return this.ccodtipdocField;
            }
            set
            {
                this.ccodtipdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string vnumdoc
        {
            get
            {
                return this.vnumdocField;
            }
            set
            {
                this.vnumdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime dfecdoc
        {
            get
            {
                return this.dfecdocField;
            }
            set
            {
                this.dfecdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string vuniorgdst
        {
            get
            {
                return this.vuniorgdstField;
            }
            set
            {
                this.vuniorgdstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string vnomdst
        {
            get
            {
                return this.vnomdstField;
            }
            set
            {
                this.vnomdstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string vnomcardst
        {
            get
            {
                return this.vnomcardstField;
            }
            set
            {
                this.vnomcardstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string vasu
        {
            get
            {
                return this.vasuField;
            }
            set
            {
                this.vasuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int snumanx
        {
            get
            {
                return this.snumanxField;
            }
            set
            {
                this.snumanxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int snumfol
        {
            get
            {
                return this.snumfolField;
            }
            set
            {
                this.snumfolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=15)]
        public byte[] bpdfdoc
        {
            get
            {
                return this.bpdfdocField;
            }
            set
            {
                this.bpdfdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string vnomdoc
        {
            get
            {
                return this.vnomdocField;
            }
            set
            {
                this.vnomdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lstanexos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public DocumentoAnexo[] lstanexos
        {
            get
            {
                return this.lstanexosField;
            }
            set
            {
                this.lstanexosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string vurldocanx
        {
            get
            {
                return this.vurldocanxField;
            }
            set
            {
                this.vurldocanxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ctipdociderem
        {
            get
            {
                return this.ctipdocideremField;
            }
            set
            {
                this.ctipdocideremField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string vnumdociderem
        {
            get
            {
                return this.vnumdocideremField;
            }
            set
            {
                this.vnumdocideremField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class DocumentoAnexo
    {
        
        private string vnomdocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vnomdoc
        {
            get
            {
                return this.vnomdocField;
            }
            set
            {
                this.vnomdocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/")]
    public partial class RespuestaTramite
    {
        
        private string vcodresField;
        
        private string vdesresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vcodres
        {
            get
            {
                return this.vcodresField;
            }
            set
            {
                this.vcodresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vdesres
        {
            get
            {
                return this.vdesresField;
            }
            set
            {
                this.vdesresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionarTramiteResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class recepcionarTramiteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.RecepcionTramite request;
        
        public recepcionarTramiteResponse()
        {
        }
        
        public recepcionarTramiteResponse(svrIOTramiteDesarrollo.RecepcionTramite request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionarTramiteResponseResponse", WrapperNamespace="http://ws.wsiopidetramite.segdi.gob.pe/", IsWrapped=true)]
    public partial class recepcionarTramiteResponseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsiopidetramite.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrIOTramiteDesarrollo.RespuestaTramite @return;
        
        public recepcionarTramiteResponseResponse()
        {
        }
        
        public recepcionarTramiteResponseResponse(svrIOTramiteDesarrollo.RespuestaTramite @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IOTramiteChannel : svrIOTramiteDesarrollo.IOTramite, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OTramiteClient : System.ServiceModel.ClientBase<svrIOTramiteDesarrollo.IOTramite>, svrIOTramiteDesarrollo.IOTramite
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OTramiteClient() : 
                base(OTramiteClient.GetDefaultBinding(), OTramiteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IOTramitePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTramiteClient(EndpointConfiguration endpointConfiguration) : 
                base(OTramiteClient.GetBindingForEndpoint(endpointConfiguration), OTramiteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTramiteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OTramiteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTramiteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OTramiteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTramiteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.cargoResponseResponse> svrIOTramiteDesarrollo.IOTramite.cargoResponseAsync(svrIOTramiteDesarrollo.cargoResponse request)
        {
            return base.Channel.cargoResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrIOTramiteDesarrollo.cargoResponseResponse> cargoResponseAsync(svrIOTramiteDesarrollo.CargoTramite request)
        {
            svrIOTramiteDesarrollo.cargoResponse inValue = new svrIOTramiteDesarrollo.cargoResponse();
            inValue.request = request;
            return ((svrIOTramiteDesarrollo.IOTramite)(this)).cargoResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.consultarTramiteResponseResponse> svrIOTramiteDesarrollo.IOTramite.consultarTramiteResponseAsync(svrIOTramiteDesarrollo.consultarTramiteResponse request)
        {
            return base.Channel.consultarTramiteResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrIOTramiteDesarrollo.consultarTramiteResponseResponse> consultarTramiteResponseAsync(svrIOTramiteDesarrollo.ConsultaTramite request)
        {
            svrIOTramiteDesarrollo.consultarTramiteResponse inValue = new svrIOTramiteDesarrollo.consultarTramiteResponse();
            inValue.request = request;
            return ((svrIOTramiteDesarrollo.IOTramite)(this)).consultarTramiteResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.getTipoDocumentoResponse> svrIOTramiteDesarrollo.IOTramite.getTipoDocumentoAsync(svrIOTramiteDesarrollo.getTipoDocumento request)
        {
            return base.Channel.getTipoDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrIOTramiteDesarrollo.getTipoDocumentoResponse> getTipoDocumentoAsync()
        {
            svrIOTramiteDesarrollo.getTipoDocumento inValue = new svrIOTramiteDesarrollo.getTipoDocumento();
            return ((svrIOTramiteDesarrollo.IOTramite)(this)).getTipoDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrIOTramiteDesarrollo.recepcionarTramiteResponseResponse> svrIOTramiteDesarrollo.IOTramite.recepcionarTramiteResponseAsync(svrIOTramiteDesarrollo.recepcionarTramiteResponse request)
        {
            return base.Channel.recepcionarTramiteResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrIOTramiteDesarrollo.recepcionarTramiteResponseResponse> recepcionarTramiteResponseAsync(svrIOTramiteDesarrollo.RecepcionTramite request)
        {
            svrIOTramiteDesarrollo.recepcionarTramiteResponse inValue = new svrIOTramiteDesarrollo.recepcionarTramiteResponse();
            inValue.request = request;
            return ((svrIOTramiteDesarrollo.IOTramite)(this)).recepcionarTramiteResponseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IOTramitePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IOTramitePort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.21.11:8080/wsiopidetramite/IOTramite");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OTramiteClient.GetBindingForEndpoint(EndpointConfiguration.IOTramitePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OTramiteClient.GetEndpointAddress(EndpointConfiguration.IOTramitePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IOTramitePort,
        }
    }
}
