//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace svrEntidadDesarrollo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/", ConfigurationName="svrEntidadDesarrollo.Entidad")]
    public interface Entidad
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrEntidadDesarrollo.getListaEntidadResponse> getListaEntidadAsync(svrEntidadDesarrollo.getListaEntidad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrEntidadDesarrollo.validarEntidadResponse> validarEntidadAsync(svrEntidadDesarrollo.validarEntidad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<svrEntidadDesarrollo.getListaEntidad2Response> getListaEntidad2Async(svrEntidadDesarrollo.getListaEntidad2 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/")]
    public partial class EntidadBean
    {
        
        private int sidentField;
        
        private int sidpadentField;
        
        private string vnomentField;
        
        private string vrucentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int sident
        {
            get
            {
                return this.sidentField;
            }
            set
            {
                this.sidentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int sidpadent
        {
            get
            {
                return this.sidpadentField;
            }
            set
            {
                this.sidpadentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vnoment
        {
            get
            {
                return this.vnomentField;
            }
            set
            {
                this.vnomentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vrucent
        {
            get
            {
                return this.vrucentField;
            }
            set
            {
                this.vrucentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/")]
    public partial class EntidadBean2
    {
        
        private int sidentField;
        
        private int sidpadentField;
        
        private string vnomentField;
        
        private string vrucentField;
        
        private EntidadBean2[] lstEntidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int sident
        {
            get
            {
                return this.sidentField;
            }
            set
            {
                this.sidentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int sidpadent
        {
            get
            {
                return this.sidpadentField;
            }
            set
            {
                this.sidpadentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vnoment
        {
            get
            {
                return this.vnomentField;
            }
            set
            {
                this.vnomentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vrucent
        {
            get
            {
                return this.vrucentField;
            }
            set
            {
                this.vrucentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lstEntidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public EntidadBean2[] lstEntidad
        {
            get
            {
                return this.lstEntidadField;
            }
            set
            {
                this.lstEntidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListaEntidad", WrapperNamespace="http://ws.wsentidad.segdi.gob.pe/", IsWrapped=true)]
    public partial class getListaEntidad
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sidcatent;
        
        public getListaEntidad()
        {
        }
        
        public getListaEntidad(int sidcatent)
        {
            this.sidcatent = sidcatent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListaEntidadResponse", WrapperNamespace="http://ws.wsentidad.segdi.gob.pe/", IsWrapped=true)]
    public partial class getListaEntidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrEntidadDesarrollo.EntidadBean[] @return;
        
        public getListaEntidadResponse()
        {
        }
        
        public getListaEntidadResponse(svrEntidadDesarrollo.EntidadBean[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarEntidad", WrapperNamespace="http://ws.wsentidad.segdi.gob.pe/", IsWrapped=true)]
    public partial class validarEntidad
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vrucent;
        
        public validarEntidad()
        {
        }
        
        public validarEntidad(string vrucent)
        {
            this.vrucent = vrucent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarEntidadResponse", WrapperNamespace="http://ws.wsentidad.segdi.gob.pe/", IsWrapped=true)]
    public partial class validarEntidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public validarEntidadResponse()
        {
        }
        
        public validarEntidadResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListaEntidad2", WrapperNamespace="http://ws.wsentidad.segdi.gob.pe/", IsWrapped=true)]
    public partial class getListaEntidad2
    {
        
        public getListaEntidad2()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListaEntidad2Response", WrapperNamespace="http://ws.wsentidad.segdi.gob.pe/", IsWrapped=true)]
    public partial class getListaEntidad2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.wsentidad.segdi.gob.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public svrEntidadDesarrollo.EntidadBean2[] @return;
        
        public getListaEntidad2Response()
        {
        }
        
        public getListaEntidad2Response(svrEntidadDesarrollo.EntidadBean2[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface EntidadChannel : svrEntidadDesarrollo.Entidad, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EntidadClient : System.ServiceModel.ClientBase<svrEntidadDesarrollo.Entidad>, svrEntidadDesarrollo.Entidad
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EntidadClient() : 
                base(EntidadClient.GetDefaultBinding(), EntidadClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EntidadPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadClient(EndpointConfiguration endpointConfiguration) : 
                base(EntidadClient.GetBindingForEndpoint(endpointConfiguration), EntidadClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EntidadClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EntidadClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrEntidadDesarrollo.getListaEntidadResponse> svrEntidadDesarrollo.Entidad.getListaEntidadAsync(svrEntidadDesarrollo.getListaEntidad request)
        {
            return base.Channel.getListaEntidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrEntidadDesarrollo.getListaEntidadResponse> getListaEntidadAsync(int sidcatent)
        {
            svrEntidadDesarrollo.getListaEntidad inValue = new svrEntidadDesarrollo.getListaEntidad();
            inValue.sidcatent = sidcatent;
            return ((svrEntidadDesarrollo.Entidad)(this)).getListaEntidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrEntidadDesarrollo.validarEntidadResponse> svrEntidadDesarrollo.Entidad.validarEntidadAsync(svrEntidadDesarrollo.validarEntidad request)
        {
            return base.Channel.validarEntidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<svrEntidadDesarrollo.validarEntidadResponse> validarEntidadAsync(string vrucent)
        {
            svrEntidadDesarrollo.validarEntidad inValue = new svrEntidadDesarrollo.validarEntidad();
            inValue.vrucent = vrucent;
            return ((svrEntidadDesarrollo.Entidad)(this)).validarEntidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<svrEntidadDesarrollo.getListaEntidad2Response> svrEntidadDesarrollo.Entidad.getListaEntidad2Async(svrEntidadDesarrollo.getListaEntidad2 request)
        {
            return base.Channel.getListaEntidad2Async(request);
        }
        
        public System.Threading.Tasks.Task<svrEntidadDesarrollo.getListaEntidad2Response> getListaEntidad2Async()
        {
            svrEntidadDesarrollo.getListaEntidad2 inValue = new svrEntidadDesarrollo.getListaEntidad2();
            return ((svrEntidadDesarrollo.Entidad)(this)).getListaEntidad2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EntidadPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EntidadPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.21.11:8080/wsentidad/Entidad");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EntidadClient.GetBindingForEndpoint(EndpointConfiguration.EntidadPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EntidadClient.GetEndpointAddress(EndpointConfiguration.EntidadPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EntidadPort,
        }
    }
}
